import Head from "next/head";

export default function Profile() {
  return (
    <>
      <Head>
        <title>This Page Profile</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <p className="bg-orange-700 p-6 text-center h-[calc(100vh-6rem)] flex items-center justify-center">
        Profile
      </p>
    </>
  );
}
